### ISSUE TITLE
Code Not Working

### ISSUE THREAD

**Issue by RAVI77321** [sbis04/rapyd_sdk_flutter#2]
I downloaded code but not running, so please provide latest code. I found there is not main.dart file in the project.

**Comment by sbis04** [comment]
This is a pure-Dart package, it doesn't require a `main.dart` file.

To use this package in your Flutter project run the following command from the project directory:

```sh
flutter pub add rapyd
```

Or, if you want to use in your Dart project:

```sh
dart pub add rapyd
```
